"""CCSDS Conjunction Data Message (CDM) generator.

Generates CDM-compliant text output per CCSDS 508.0-B-1 standard,
the format used by 18th Space Defense Squadron and commercial SSA
providers for conjunction notification.

Reference: CCSDS 508.0-B-1, "Conjunction Data Message" (June 2013).
"""

from __future__ import annotations

from datetime import datetime, timezone
from textwrap import dedent

from sda.models import ConjunctionEvent, TLERecord


def generate_cdm(
    event: ConjunctionEvent,
    tle_primary: TLERecord | None = None,
    tle_secondary: TLERecord | None = None,
    collision_probability: float | None = None,
    message_id: str | None = None,
    originator: str = "SDA-COLLISION-PREDICTOR",
) -> str:
    """Generate a CCSDS-formatted Conjunction Data Message.

    Parameters
    ----------
    event : ConjunctionEvent — the conjunction to report
    tle_primary : optional TLERecord for additional metadata
    tle_secondary : optional TLERecord for additional metadata
    collision_probability : optional Pc value to include
    message_id : optional unique message ID
    originator : message originator identifier

    Returns
    -------
    CDM-formatted string
    """
    now = datetime.now(timezone.utc)
    if message_id is None:
        message_id = f"{event.primary}_{event.secondary}_{now.strftime('%Y%m%d%H%M%S')}"

    tca_str = event.tca.strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3]
    creation_str = now.strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3]

    primary_name = event.primary_name or f"OBJECT {event.primary}"
    secondary_name = event.secondary_name or f"OBJECT {event.secondary}"

    primary_epoch = tle_primary.epoch.strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] if tle_primary else "N/A"
    secondary_epoch = tle_secondary.epoch.strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] if tle_secondary else "N/A"

    primary_intl = _extract_intl_designator(tle_primary) if tle_primary else "N/A"
    secondary_intl = _extract_intl_designator(tle_secondary) if tle_secondary else "N/A"

    pc_line = ""
    if collision_probability is not None:
        pc_line = f"COLLISION_PROBABILITY          = {collision_probability:.6e}\n"

    cdm = dedent(f"""\
        CCSDS_CDM_VERS                = 1.0
        CREATION_DATE                 = {creation_str}
        ORIGINATOR                    = {originator}
        MESSAGE_ID                    = {message_id}
        TCA                           = {tca_str}
        MISS_DISTANCE                 = {event.miss_distance_km:.6f} [km]
        RELATIVE_SPEED                = {event.relative_velocity_km_s:.6f} [km/s]
        {pc_line}COMMENT Risk classification: {event.risk.value}
        COMMENT Generated by SDA Collision Predictor

        OBJECT                        = OBJECT1
        OBJECT_DESIGNATOR             = {event.primary}
        CATALOG_NAME                  = SATCAT
        OBJECT_NAME                   = {primary_name}
        INTERNATIONAL_DESIGNATOR      = {primary_intl}
        EPHEMERIS_NAME                = SGP4
        COVARIANCE_METHOD             = CALCULATED
        REF_FRAME                     = EME2000
        GRAVITY_MODEL                 = WGS-72
        ATMOSPHERIC_MODEL             = NONE
        SOLAR_RAD_PRESSURE            = NO
        EARTH_TIDES                   = NO
        TIME_LASTOB_START             = {primary_epoch}
        TIME_LASTOB_END               = {primary_epoch}

        OBJECT                        = OBJECT2
        OBJECT_DESIGNATOR             = {event.secondary}
        CATALOG_NAME                  = SATCAT
        OBJECT_NAME                   = {secondary_name}
        INTERNATIONAL_DESIGNATOR      = {secondary_intl}
        EPHEMERIS_NAME                = SGP4
        COVARIANCE_METHOD             = CALCULATED
        REF_FRAME                     = EME2000
        GRAVITY_MODEL                 = WGS-72
        ATMOSPHERIC_MODEL             = NONE
        SOLAR_RAD_PRESSURE            = NO
        EARTH_TIDES                   = NO
        TIME_LASTOB_START             = {secondary_epoch}
        TIME_LASTOB_END               = {secondary_epoch}
    """)

    return cdm


def _extract_intl_designator(tle: TLERecord) -> str:
    """Extract international designator from TLE line 1 (columns 9-17)."""
    try:
        return tle.line1[9:17].strip()
    except (IndexError, AttributeError):
        return "N/A"


def generate_cdm_batch(
    events: list[ConjunctionEvent],
    tle_lookup: dict[int, TLERecord] | None = None,
    pc_lookup: dict[tuple[int, int], float] | None = None,
    originator: str = "SDA-COLLISION-PREDICTOR",
) -> list[dict]:
    """Generate CDMs for multiple conjunction events.

    Returns list of dicts with keys: primary, secondary, risk, cdm_text.
    """
    results = []
    for event in events:
        tle_p = tle_lookup.get(event.primary) if tle_lookup else None
        tle_s = tle_lookup.get(event.secondary) if tle_lookup else None
        pc = None
        if pc_lookup:
            pc = pc_lookup.get((event.primary, event.secondary))

        cdm_text = generate_cdm(
            event=event,
            tle_primary=tle_p,
            tle_secondary=tle_s,
            collision_probability=pc,
            originator=originator,
        )
        results.append({
            "primary": event.primary,
            "secondary": event.secondary,
            "risk": event.risk.value,
            "cdm_text": cdm_text,
        })

    return results
